V1.0
quebramadeira/docker-hadoop pull request #1
Opened 2022-02-22 08:58 UTC by quebramadeira

@yegorgeorgiyev  comment me
@nikita-safonov comment me
@Shlepanets comment me
@Cakemanator comment me

2022-02-24 14:58 UTC, Cakemanator requested changes

2022-02-24 14:58 UTC, Cakemanator commented on README.md
> +  - hadoop-3.1.2.tar.gz file from https://hadoop.apache.org/release/3.1.2.html
Better to use a link https://archive.apache.org/dist/hadoop/common/hadoop-3.1.2/hadoop-3.1.2.tar.gz

2022-02-24 14:58 UTC, Cakemanator commented on README.md
> +  - docker-compose up -d
![image](https://user-images.githubusercontent.com/43520795/155544337-86db85b5-c218-4602-99e8-39433240496a.png)
Created network:
![image](https://user-images.githubusercontent.com/43520795/155546677-e39ba6e6-09a4-416d-973b-b86631a3728e.png)

2022-02-24 14:58 UTC, Cakemanator commented on headnode/Dockerfile
> +MAINTAINER Alexander Nemchinov <quantumrods@gmail.com>
Please use more best practices for Dockerfiles

2022-02-24 14:58 UTC, Cakemanator commented on worker/Dockerfile
> +MAINTAINER Alexander Nemchinov <quantumrods@gmail.com>
Please use more best practices for Dockerfiles

2022-02-25 07:42 UTC, quebramadeira commented on README.md
> +  - docker-compose up -d
I have used this line for network creation, everything works fine, even with a new VM:
`docker network create --gateway 192.168.10.1 --subnet 192.168.10.0/24 hadoop`

2022-02-25 07:43 UTC, quebramadeira commented on headnode/Dockerfile
> +MAINTAINER Alexander Nemchinov <quantumrods@gmail.com>
`FROM centos:8`

2022-02-25 07:43 UTC, quebramadeira commented on worker/Dockerfile
> +MAINTAINER Alexander Nemchinov <quantumrods@gmail.com>
`FROM centos:8`

2022-03-03 13:32 UTC, Cakemanator requested changes

2022-03-03 13:32 UTC, Cakemanator commented on headnode/Dockerfile
> +MAINTAINER Alexander Nemchinov <quantumrods@gmail.com>
What about optimization of repeated instructions (RUN, COPY, etc)?

2022-03-03 13:32 UTC, Cakemanator commented on worker/Dockerfile
> +MAINTAINER Alexander Nemchinov <quantumrods@gmail.com>
What about optimization of repeated instructions (RUN, COPY, etc)?

2022-03-06 10:38 UTC, quebramadeira commented on headnode/Dockerfile
> +MAINTAINER Alexander Nemchinov <quantumrods@gmail.com>
FROM centos:8
MAINTAINER Alexander Nemchinov <[quantumrods@gmail.com](mailto:quantumrods@gmail.com)>
WORKDIR /etc/yum.repos.d/
RUN sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-* \
        && sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-* \
        && yum -y update && yum -y remove java && yum install -y  java-1.8.0-openjdk
WORKDIR /opt
COPY hadoop-3.1.2.tar.gz /opt
RUN tar -xf hadoop-3.1.2.tar.gz && mkdir /usr/local/hadoop \
        &&  ln -s /opt/hadoop-3.1.2/ /usr/local/hadoop/current
COPY config/hadoop-env.sh config/core-site.xml config/hdfs-site.xml config/yarn-site.xml /usr/local/hadoop/current/etc/hadoop/
WORKDIR /usr/local/hadoop/current/etc/hadoop
RUN sed -i 's:%PATH_TO_OPENJDK8_INSTALLATION%:/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.312.b07-2.el8_5.x86_64/jre:g' hadoop-env.sh \
        && sed -i 's:%PATH_TO_HADOOP_INSTALLATION:/usr/local/hadoop/current:g' hadoop-env.sh \
        && sed -i 's:%HADOOP_HEAP_SIZE%:512M:g' hadoop-env.sh \
        && sed -i 's:%HDFS_NAMENODE_HOSTNAME%:headnode:g' core-site.xml \
        && sed -i 's:%NAMENODE_DIRS%:/opt/mount1/namenode-dir,/opt/mount2/namenode-dir:g' hdfs-site.xml \
        && sed -i 's:%DATANODE_DIRS%:/opt/mount1/datanode-dir,/opt/mount2/datanode-dir:g' hdfs-site.xml \
        && sed -i 's:%YARN_RESOURCE_MANAGER_HOSTNAME%:headnode:g' yarn-site.xml \
        && sed -i 's:%NODE_MANAGER_LOCAL_DIR%:/opt/mount1/nodemanager-local-dir,/opt/mount2/nodemanager-local-dir:g' yarn-site.xml \
        && sed -i 's:%NODE_MANAGER_LOG_DIR%:/opt/mount1/nodemanager-log-dir,/opt/mount2/nodemanager-log-dir:g' yarn-site.xml
ENV HADOOP_HOME="/usr/local/hadoop/current"
RUN groupadd -g 4000 hadoop && useradd -g hadoop -u 1500 hadoop \
        && useradd -g hadoop -u 1600 yarn \
        && useradd -g hadoop -u 1700 hdfs \
        && mkdir /opt/hadoop-3.1.2/logs \
        && chown :hadoop /opt/hadoop-3.1.2/logs \
        && setfacl -d -R -m g:hadoop:rwx /opt/hadoop-3.1.2/logs \
        && setfacl -R -m g:hadoop:rwx /opt/hadoop-3.1.2/logs \
        && mkdir -p /opt/mount1/namenode-dir \
        && mkdir -p /opt/mount2/namenode-dir \
        && chown hdfs /opt/mount1/namenode-dir \
        && chown hdfs /opt/mount2/namenode-dir \
        && chown :hadoop /opt/mount1/namenode-dir \
    && chown :hadoop /opt/mount2/namenode-dir
VOLUME /opt/mount1 opt/mount2
COPY headnode/runheadnode.sh /runheadnode.sh
RUN chmod a+x /runheadnode.sh
CMD ["/runheadnode.sh"]

2023-01-25 09:54 UTC, merged